export const IMAGES_RES = {
  homeBackground: require('../../assets/images/bg.png'),
  notifIcon: require('../../assets/images/notif.png'),
  cardGradient: {
    cardPinkRight: require('../../assets/images/cardPinkRightGradient.png'),
    cardBlueLeft: require('../../assets/images/cardCyanLeftGradient.png'),
  },
  progressBar: require('../../assets/images/progressBar.png'),
  badge: require('../../assets/images/badge.png'),
  arrow: {
    pink_right: require('../../assets/images/cardRightPink.png'),
  },
  searchPlus: require('../../assets/images/searchPlus.png'),
  banner: require('../../assets/images/banner1.png'),
  tabIcon: {
    home: require('../../assets/images/ic_home_active.png'),
    home_inactive: require('../../assets/images/ic_home_inactive.png'),
    order: require('../../assets/images/ic_order_active.png'),
    order_inactive: require('../../assets/images/ic_order_inactive.png'),
    playcard: require('../../assets/images/ic_playcard.png'),
    outlet: require('../../assets/images/ic_outlet_active.png'),
    outlet_inactive: require('../../assets/images/ic_outlet_inactive.png'),
    account: require('../../assets/images/ic_account_active.png'),
    account_inactive: require('../../assets/images/ic_account_inactive.png'),
  },
  bronzeCard: require('../../assets/images/bronzeCard.png'),
  bronzeBadge: require('../../assets/images/levelBronze.png'),
  playcardLogo: require('../../assets/images/playcardLogo.png'),
  playcardLogoTransparent: require('../../assets/images/playCardnoBg.png'),
  playmilesLogo: require('../../assets/images/playmilesLogo.png'),
  voucherIcon: require('../../assets/images/voucherIcon.png'),
  voucherBackground: require('../../assets/images/voucherBg.png'),
  profileIcon: {
    security: require('../../assets/images/ic_security.png'),
    notification: require('../../assets/images/ic_notif.png'),
    help: require('../../assets/images/ic_help.png'),
    other: require('../../assets/images/ic_other.png'),
  },
  button: {
    back: require('../../assets/images/back.png'),
    exit: require('../../assets/images/exit.png'),
  },
  playcardBackground: require('../../assets/images/playCardBg.png'),
  lockIcon: require('../../assets/images/ic_lock.png'),
  lockIconDark: require('../../assets/images/ic_lock_dark.png'),
  rpIcon: require('../../assets/images/ic_rp.png'),
  exampleQR: require('../../assets/images/ex_qr.png'),
  exampleCity: require('../../assets/images/ex_city.png'),
};
